### ISSUE TITLE
Anti-bot (anti-raid, etc.)

### ISSUE THREAD

**Issue by Aisuruneko** [TMC-Software/TheCodingBot#6]
When the `guildMemberAdd` event fires, the bot needs to determine if the "user" added is a bot that could be a raider, etc.

**Comment by IDeletedSystem64** [comment]
I feel this should work by:
1. Checking the account creation date, if it is recent, monitor its message activity for a period of time, say 24 hours?
2. If the account begins trying to send invites, sus links (these will be kept in a json. like the domain names of Nitro scams.), or spamming messages in channels, Automatically take actions specified by the server owner. 
3. This should also automatically take a lighter action (like a mute) on normal 'trusted' accounts if they send links that are the fake Nitro links. only problem would be keeping the list up-to-date..

**Comment by Aisuruneko** [comment]
Hi there!

1) Checking the account is easy but monitoring its message history would be a pain as the bot would have to keep up with how said account interacts. This could be memory consuming and hard on the bot. What if the bot restarts? Logging this stuff to a database would also be a pain in its own ways. A problem that does make me think is that as some scams are also sent in DMs, so how can the bot monitor those?
2) Sending invites and spamming are technically apart of moderation. This will be implemented there. For the bad domains, check the 3rd part of this list.
3) Discord has implemented "blacklisted domains" which may already catch the link once reported. Although there can be a simple way to fetch the blacklisted domains and check (https://cdn.discordapp.com/bad-domains/hashes.json). However, this is a pain as there are over 2k+ hashed bad domains and then for the bot to bother converting the hashes to text and checking if the message content contains a bad domain is memory consuming.

**Comment by Aisuruneko** [comment]
Until there is a definite and efficient way of doing this, I'm going to remove this from the v5 Release milestone.

**Comment by Aisuruneko** [comment]
Version 6 will 100% be getting the Advanced Moderation System™ (AMS).

**Comment by IDeletedSystem64** [comment]
Amazon Moderation System

**Comment by Aisuruneko** [comment]
Closing this due to v6 not going to be released. Apologies for this.
