### ISSUE TITLE
Add more events™

### ISSUE THREAD

**Issue by Aisuruneko** [TMC-Software/TheCodingBot#7]
**NOTE:** v4 did not log channel, role, and most guild events. In v5, we will capture all events.

### Channel
 - [x] channelCreate (b16aafa)
 - [x] channelDelete (b16aafa)
 - [x] channelUpdate (b16aafa)

### Emoji
 - [x] emojiCreate (#23)
 - [x] emojiDelete (#23)
 - [x] emojiUpdate (#23)

### Guild
 - [x] guildCreate (#23)
 - [x] guildDelete (d52f52b)
 - [x] guildUpdate (#23)

### Guild Ban
 - [x] guildBanAdd (#23)
 - [x] guildBanRemove (#23)

### Guild Member
 - [x] guildMemberAdd (d8e6c22, #23)
 - [x] guildMemberRemove (#13, d8e6c22, #23)
 - [x] guildMemberUpdate (#23)

### Message
 - [x] message
 - [x] messageDelete
 - [x] #15
 - [x] messageUpdate

### Roles
 - [x] roleCreate (b16aafa)
 - [x] roleDelete (b16aafa)
 - [x] roleUpdate (b16aafa)

### Invites
 - [x] inviteCreate (#23)
 - [x] inviteDelete (#23)

*List is subject to change.*

**Notable problems:** The `loggingX` row part in `serverSettings` in DB may become a huge mess...
`loggingDeleteChannel`, `loggingEditChannel`, `loggingRoleCreateChannel`, `loggingRoleUpdateChannel`, `loggingRoleDeleteChannel`, `loggingEmojiCreateChannel`, `loggingEmojiUpdateChannel`, `loggingEmojiDeleteChannel`... you see the problem yet?

**Comment by Mazzen790** [comment]
👁👄👁

**Comment by IDeletedSystem64** [comment]
Very cool.
